// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: matrix.capnp

#include "matrix.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<31> b_d5e20d45027a2de2 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    226,  45, 122,   2,  69,  13, 226, 213,
     13,   0,   0,   0,   3,   0,   0,   0,
    225,  64, 207, 190, 203,  71,  81, 191,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     22,   0,   0,   0,  82,   0,   0,   0,
     21,   0,   0,   0, 210,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  71,   0,   0,   0,
     73,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  87, 111, 114, 107, 101,
    114,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   5,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    221, 166, 111, 122, 169,  26, 100, 203,
    226,  21, 104, 114, 173, 180, 137, 159,
     17,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      9,   0,   0,   0,   7,   0,   0,   0,
    115, 101, 110, 100,  84,  97, 115, 107,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
      0,   0,   0,   0,   1,   0,   1,   0, }
};
::capnp::word const* const bp_d5e20d45027a2de2 = b_d5e20d45027a2de2.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_d5e20d45027a2de2[] = {
  &s_9f89b4ad726815e2,
  &s_cb641aa97a6fa6dd,
};
static const uint16_t m_d5e20d45027a2de2[] = {0};
const ::capnp::_::RawSchema s_d5e20d45027a2de2 = {
  0xd5e20d45027a2de2, b_d5e20d45027a2de2.words, 31, d_d5e20d45027a2de2, m_d5e20d45027a2de2,
  2, 1, nullptr, nullptr, nullptr, { &s_d5e20d45027a2de2, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<35> b_cb641aa97a6fa6dd = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    221, 166, 111, 122, 169,  26, 100, 203,
     26,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  82,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  87, 111, 114, 107, 101,
    114,  46, 115, 101, 110, 100,  84,  97,
    115, 107,  36,  80,  97, 114,  97, 109,
    115,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    116,  97, 115, 107,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    135, 180, 243,  57,  73, 234, 122, 129,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_cb641aa97a6fa6dd = b_cb641aa97a6fa6dd.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_cb641aa97a6fa6dd[] = {
  &s_817aea4939f3b487,
};
static const uint16_t m_cb641aa97a6fa6dd[] = {0};
static const uint16_t i_cb641aa97a6fa6dd[] = {0};
const ::capnp::_::RawSchema s_cb641aa97a6fa6dd = {
  0xcb641aa97a6fa6dd, b_cb641aa97a6fa6dd.words, 35, d_cb641aa97a6fa6dd, m_cb641aa97a6fa6dd,
  1, 1, i_cb641aa97a6fa6dd, nullptr, nullptr, { &s_cb641aa97a6fa6dd, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<19> b_9f89b4ad726815e2 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    226,  21, 104, 114, 173, 180, 137, 159,
     26,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  90,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  87, 111, 114, 107, 101,
    114,  46, 115, 101, 110, 100,  84,  97,
    115, 107,  36,  82, 101, 115, 117, 108,
    116, 115,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_9f89b4ad726815e2 = b_9f89b4ad726815e2.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_9f89b4ad726815e2 = {
  0x9f89b4ad726815e2, b_9f89b4ad726815e2.words, 19, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_9f89b4ad726815e2, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<51> b_b2b2d3b2ab0357e3 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    227,  87,   3, 171, 178, 211, 178, 178,
     13,   0,   0,   0,   3,   0,   0,   0,
    225,  64, 207, 190, 203,  71,  81, 191,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     84,   0,   0,   0, 254,   0,   0,   0,
     21,   0,   0,   0, 218,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 199,   0,   0,   0,
    153,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  77,  97, 110,  97, 103,
    101, 114,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     12,   0,   0,   0,   3,   0,   5,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    181,   7, 248,  69,  16, 155, 241, 199,
    137, 244, 175, 107, 148, 130,  78, 142,
     81,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     69,   0,   0,   0,   7,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
    203, 211, 125, 233,  77, 252, 107, 223,
     90, 231,  71, 118, 111, 153, 146, 200,
     57,   0,   0,   0,  90,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     49,   0,   0,   0,   7,   0,   0,   0,
      2,   0,   0,   0,   0,   0,   0,   0,
     39,  89, 196, 120,   9, 129, 254, 165,
    111,  16, 190,  80,  37,   1, 175, 238,
     37,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     25,   0,   0,   0,   7,   0,   0,   0,
    115, 116,  97, 114, 116,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    115, 117,  98, 109, 105, 116,  84,  97,
    115, 107,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
    112, 105, 110, 103,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
      0,   0,   0,   0,   1,   0,   1,   0, }
};
::capnp::word const* const bp_b2b2d3b2ab0357e3 = b_b2b2d3b2ab0357e3.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_b2b2d3b2ab0357e3[] = {
  &s_8e4e82946baff489,
  &s_a5fe810978c45927,
  &s_c7f19b1045f807b5,
  &s_c892996f7647e75a,
  &s_df6bfc4de97dd3cb,
  &s_eeaf012550be106f,
};
static const uint16_t m_b2b2d3b2ab0357e3[] = {2, 0, 1};
const ::capnp::_::RawSchema s_b2b2d3b2ab0357e3 = {
  0xb2b2d3b2ab0357e3, b_b2b2d3b2ab0357e3.words, 51, d_b2b2d3b2ab0357e3, m_b2b2d3b2ab0357e3,
  6, 3, nullptr, nullptr, nullptr, { &s_b2b2d3b2ab0357e3, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<35> b_c7f19b1045f807b5 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    181,   7, 248,  69,  16, 155, 241, 199,
     27,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  66,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  77,  97, 110,  97, 103,
    101, 114,  46, 115, 116,  97, 114, 116,
     36,  80,  97, 114,  97, 109, 115,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  74,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   3,   0,   1,   0,
     24,   0,   0,   0,   2,   0,   1,   0,
    108, 105, 115, 116, 101, 110, 101, 114,
      0,   0,   0,   0,   0,   0,   0,   0,
     17,   0,   0,   0,   0,   0,   0,   0,
    226,  45, 122,   2,  69,  13, 226, 213,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     17,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_c7f19b1045f807b5 = b_c7f19b1045f807b5.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_c7f19b1045f807b5[] = {
  &s_d5e20d45027a2de2,
};
static const uint16_t m_c7f19b1045f807b5[] = {0};
static const uint16_t i_c7f19b1045f807b5[] = {0};
const ::capnp::_::RawSchema s_c7f19b1045f807b5 = {
  0xc7f19b1045f807b5, b_c7f19b1045f807b5.words, 35, d_c7f19b1045f807b5, m_c7f19b1045f807b5,
  1, 1, i_c7f19b1045f807b5, nullptr, nullptr, { &s_c7f19b1045f807b5, nullptr, nullptr, 0, 0, nullptr }, true
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<19> b_8e4e82946baff489 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    137, 244, 175, 107, 148, 130,  78, 142,
     27,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  74,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  77,  97, 110,  97, 103,
    101, 114,  46, 115, 116,  97, 114, 116,
     36,  82, 101, 115, 117, 108, 116, 115,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_8e4e82946baff489 = b_8e4e82946baff489.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_8e4e82946baff489 = {
  0x8e4e82946baff489, b_8e4e82946baff489.words, 19, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_8e4e82946baff489, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<35> b_df6bfc4de97dd3cb = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    203, 211, 125, 233,  77, 252, 107, 223,
     27,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 106,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  77,  97, 110,  97, 103,
    101, 114,  46, 115, 117,  98, 109, 105,
    116,  84,  97, 115, 107,  36,  80,  97,
    114,  97, 109, 115,   0,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    116,  97, 115, 107,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    135, 180, 243,  57,  73, 234, 122, 129,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_df6bfc4de97dd3cb = b_df6bfc4de97dd3cb.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_df6bfc4de97dd3cb[] = {
  &s_817aea4939f3b487,
};
static const uint16_t m_df6bfc4de97dd3cb[] = {0};
static const uint16_t i_df6bfc4de97dd3cb[] = {0};
const ::capnp::_::RawSchema s_df6bfc4de97dd3cb = {
  0xdf6bfc4de97dd3cb, b_df6bfc4de97dd3cb.words, 35, d_df6bfc4de97dd3cb, m_df6bfc4de97dd3cb,
  1, 1, i_df6bfc4de97dd3cb, nullptr, nullptr, { &s_df6bfc4de97dd3cb, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<35> b_c892996f7647e75a = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     90, 231,  71, 118, 111, 153, 146, 200,
     27,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 114,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  77,  97, 110,  97, 103,
    101, 114,  46, 115, 117,  98, 109, 105,
    116,  84,  97, 115, 107,  36,  82, 101,
    115, 117, 108, 116, 115,   0,   0,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    114, 101, 115, 117, 108, 116,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    159, 169,  86, 101, 159, 107,  24, 225,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_c892996f7647e75a = b_c892996f7647e75a.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_c892996f7647e75a[] = {
  &s_e1186b9f6556a99f,
};
static const uint16_t m_c892996f7647e75a[] = {0};
static const uint16_t i_c892996f7647e75a[] = {0};
const ::capnp::_::RawSchema s_c892996f7647e75a = {
  0xc892996f7647e75a, b_c892996f7647e75a.words, 35, d_c892996f7647e75a, m_c892996f7647e75a,
  1, 1, i_c892996f7647e75a, nullptr, nullptr, { &s_c892996f7647e75a, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<18> b_a5fe810978c45927 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
     39,  89, 196, 120,   9, 129, 254, 165,
     27,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  58,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  77,  97, 110,  97, 103,
    101, 114,  46, 112, 105, 110, 103,  36,
     80,  97, 114,  97, 109, 115,   0,   0, }
};
::capnp::word const* const bp_a5fe810978c45927 = b_a5fe810978c45927.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_a5fe810978c45927 = {
  0xa5fe810978c45927, b_a5fe810978c45927.words, 18, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_a5fe810978c45927, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<34> b_eeaf012550be106f = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    111,  16, 190,  80,  37,   1, 175, 238,
     27,   0,   0,   0,   1,   0,   1,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  66,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  77,  97, 110,  97, 103,
    101, 114,  46, 112, 105, 110, 103,  36,
     82, 101, 115, 117, 108, 116, 115,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  26,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    111, 107,   0,   0,   0,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_eeaf012550be106f = b_eeaf012550be106f.words;
#if !CAPNP_LITE
static const uint16_t m_eeaf012550be106f[] = {0};
static const uint16_t i_eeaf012550be106f[] = {0};
const ::capnp::_::RawSchema s_eeaf012550be106f = {
  0xeeaf012550be106f, b_eeaf012550be106f.words, 34, nullptr, m_eeaf012550be106f,
  0, 1, i_eeaf012550be106f, nullptr, nullptr, { &s_eeaf012550be106f, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<93> b_817aea4939f3b487 = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    135, 180, 243,  57,  73, 234, 122, 129,
     13,   0,   0,   0,   1,   0,   1,   0,
    225,  64, 207, 190, 203,  71,  81, 191,
      3,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   1,   0,   0, 144,   1,   0,   0,
     21,   0,   0,   0, 194,   0,   0,   0,
     29,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     25,   0,   0,   0,  31,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  84,  97, 115, 107,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     20,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    125,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    120,   0,   0,   0,   3,   0,   1,   0,
    132,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    129,   0,   0,   0,  34,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    124,   0,   0,   0,   3,   0,   1,   0,
    136,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    133,   0,   0,   0,  18,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    128,   0,   0,   0,   3,   0,   1,   0,
    140,   0,   0,   0,   2,   0,   1,   0,
      3,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   3,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    137,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    132,   0,   0,   0,   3,   0,   1,   0,
    144,   0,   0,   0,   2,   0,   1,   0,
      4,   0,   0,   0,   2,   0,   0,   0,
      0,   0,   1,   0,   4,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    141,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    136,   0,   0,   0,   3,   0,   1,   0,
    148,   0,   0,   0,   2,   0,   1,   0,
    116,  97, 115, 107,  73, 100,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    111, 112, 115,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    110,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    105, 110, 112, 117, 116,  65,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    105, 110, 112, 117, 116,  66,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_817aea4939f3b487 = b_817aea4939f3b487.words;
#if !CAPNP_LITE
static const uint16_t m_817aea4939f3b487[] = {3, 4, 2, 1, 0};
static const uint16_t i_817aea4939f3b487[] = {0, 1, 2, 3, 4};
const ::capnp::_::RawSchema s_817aea4939f3b487 = {
  0x817aea4939f3b487, b_817aea4939f3b487.words, 93, nullptr, m_817aea4939f3b487,
  0, 5, i_817aea4939f3b487, nullptr, nullptr, { &s_817aea4939f3b487, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<64> b_e1186b9f6556a99f = {
  {   0,   0,   0,   0,   6,   0,   6,   0,
    159, 169,  86, 101, 159, 107,  24, 225,
     13,   0,   0,   0,   1,   0,   1,   0,
    225,  64, 207, 190, 203,  71,  81, 191,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    146,   1,   0,   0, 223,   1,   0,   0,
     21,   0,   0,   0, 210,   0,   0,   0,
     33,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     29,   0,   0,   0, 175,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109,  97, 116, 114, 105, 120,  46,  99,
     97, 112, 110, 112,  58,  77,  97, 116,
    114, 105, 120,  82, 101, 115, 117, 108,
    116,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     12,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     69,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     64,   0,   0,   0,   3,   0,   1,   0,
     76,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     73,   0,   0,   0,  18,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     68,   0,   0,   0,   3,   0,   1,   0,
     80,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     77,   0,   0,   0,  58,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     72,   0,   0,   0,   3,   0,   1,   0,
     84,   0,   0,   0,   2,   0,   1,   0,
    116,  97, 115, 107,  73, 100,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    110,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      4,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    114, 101, 115, 117, 108, 116,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_e1186b9f6556a99f = b_e1186b9f6556a99f.words;
#if !CAPNP_LITE
static const uint16_t m_e1186b9f6556a99f[] = {1, 2, 0};
static const uint16_t i_e1186b9f6556a99f[] = {0, 1, 2};
const ::capnp::_::RawSchema s_e1186b9f6556a99f = {
  0xe1186b9f6556a99f, b_e1186b9f6556a99f.words, 64, nullptr, m_e1186b9f6556a99f,
  0, 3, i_e1186b9f6556a99f, nullptr, nullptr, { &s_e1186b9f6556a99f, nullptr, nullptr, 0, 0, nullptr }, false
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


#if !CAPNP_LITE
::capnp::Request< ::MatrixWorker::SendTaskParams,  ::MatrixWorker::SendTaskResults>
MatrixWorker::Client::sendTaskRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::MatrixWorker::SendTaskParams,  ::MatrixWorker::SendTaskResults>(
      0xd5e20d45027a2de2ull, 0, sizeHint, {true});
}
::kj::Promise<void> MatrixWorker::Server::sendTask(SendTaskContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "matrix.capnp:MatrixWorker", "sendTask",
      0xd5e20d45027a2de2ull, 0);
}
::capnp::Capability::Server::DispatchCallResult MatrixWorker::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (interfaceId) {
    case 0xd5e20d45027a2de2ull:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("matrix.capnp:MatrixWorker", interfaceId);
  }
}
::capnp::Capability::Server::DispatchCallResult MatrixWorker::Server::dispatchCallInternal(
    uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return {
        sendTask(::capnp::Capability::Server::internalGetTypedContext<
             ::MatrixWorker::SendTaskParams,  ::MatrixWorker::SendTaskResults>(context)),
        false,
        false
      };
    default:
      (void)context;
      return ::capnp::Capability::Server::internalUnimplemented(
          "matrix.capnp:MatrixWorker",
          0xd5e20d45027a2de2ull, methodId);
  }
}
#endif  // !CAPNP_LITE

// MatrixWorker
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixWorker::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixWorker::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixWorker::SendTaskParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixWorker::SendTaskParams::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixWorker::SendTaskParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixWorker::SendTaskParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixWorker::SendTaskParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixWorker::SendTaskResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixWorker::SendTaskResults::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixWorker::SendTaskResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixWorker::SendTaskResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixWorker::SendTaskResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
::capnp::Request< ::MatrixManager::StartParams,  ::MatrixManager::StartResults>
MatrixManager::Client::startRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::MatrixManager::StartParams,  ::MatrixManager::StartResults>(
      0xb2b2d3b2ab0357e3ull, 0, sizeHint, {true});
}
::kj::Promise<void> MatrixManager::Server::start(StartContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "matrix.capnp:MatrixManager", "start",
      0xb2b2d3b2ab0357e3ull, 0);
}
::capnp::Request< ::MatrixManager::SubmitTaskParams,  ::MatrixManager::SubmitTaskResults>
MatrixManager::Client::submitTaskRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::MatrixManager::SubmitTaskParams,  ::MatrixManager::SubmitTaskResults>(
      0xb2b2d3b2ab0357e3ull, 1, sizeHint, {true});
}
::kj::Promise<void> MatrixManager::Server::submitTask(SubmitTaskContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "matrix.capnp:MatrixManager", "submitTask",
      0xb2b2d3b2ab0357e3ull, 1);
}
::capnp::Request< ::MatrixManager::PingParams,  ::MatrixManager::PingResults>
MatrixManager::Client::pingRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::MatrixManager::PingParams,  ::MatrixManager::PingResults>(
      0xb2b2d3b2ab0357e3ull, 2, sizeHint, {true});
}
::kj::Promise<void> MatrixManager::Server::ping(PingContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "matrix.capnp:MatrixManager", "ping",
      0xb2b2d3b2ab0357e3ull, 2);
}
::capnp::Capability::Server::DispatchCallResult MatrixManager::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (interfaceId) {
    case 0xb2b2d3b2ab0357e3ull:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("matrix.capnp:MatrixManager", interfaceId);
  }
}
::capnp::Capability::Server::DispatchCallResult MatrixManager::Server::dispatchCallInternal(
    uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return {
        start(::capnp::Capability::Server::internalGetTypedContext<
             ::MatrixManager::StartParams,  ::MatrixManager::StartResults>(context)),
        false,
        false
      };
    case 1:
      return {
        submitTask(::capnp::Capability::Server::internalGetTypedContext<
             ::MatrixManager::SubmitTaskParams,  ::MatrixManager::SubmitTaskResults>(context)),
        false,
        false
      };
    case 2:
      return {
        ping(::capnp::Capability::Server::internalGetTypedContext<
             ::MatrixManager::PingParams,  ::MatrixManager::PingResults>(context)),
        false,
        false
      };
    default:
      (void)context;
      return ::capnp::Capability::Server::internalUnimplemented(
          "matrix.capnp:MatrixManager",
          0xb2b2d3b2ab0357e3ull, methodId);
  }
}
#endif  // !CAPNP_LITE

// MatrixManager
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixManager::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixManager::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixManager::StartParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixManager::StartParams::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixManager::StartParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixManager::StartParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixManager::StartParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixManager::StartResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixManager::StartResults::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixManager::StartResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixManager::StartResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixManager::StartResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixManager::SubmitTaskParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixManager::SubmitTaskParams::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixManager::SubmitTaskParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixManager::SubmitTaskParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixManager::SubmitTaskParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixManager::SubmitTaskResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixManager::SubmitTaskResults::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixManager::SubmitTaskResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixManager::SubmitTaskResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixManager::SubmitTaskResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixManager::PingParams
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixManager::PingParams::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixManager::PingParams::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixManager::PingParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixManager::PingParams::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixManager::PingResults
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixManager::PingResults::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixManager::PingResults::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixManager::PingResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixManager::PingResults::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixTask
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixTask::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixTask::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixTask::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixTask::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE

// MatrixResult
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr uint16_t MatrixResult::_capnpPrivate::dataWordSize;
constexpr uint16_t MatrixResult::_capnpPrivate::pointerCount;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#if !CAPNP_LITE
#if CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
constexpr ::capnp::Kind MatrixResult::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* MatrixResult::_capnpPrivate::schema;
#endif  // !CAPNP_NEED_REDUNDANT_CONSTEXPR_DECL
#endif  // !CAPNP_LITE



